development:
  # adapter: async
  adapter: redis

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  # url: redis://localhost:6379/1
  channel_prefix: vehicle-search_production
